CREATE DATABASE IF NOT EXISTS cms CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS unad CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE USER IF NOT EXISTS 'cms_admin'@'%' IDENTIFIED BY 'CmS_2026!Joomla#Lab';
CREATE USER IF NOT EXISTS 'portal_app'@'%' IDENTIFIED BY 'P0rtal_2026!Sql#Lab';

GRANT ALL PRIVILEGES ON cms.* TO 'cms_admin'@'%';
GRANT ALL PRIVILEGES ON unad.* TO 'portal_app'@'%';
FLUSH PRIVILEGES;
