server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Powered-By "Nginx 1.24 Vulnerable";
    add_header Server "Insecure-Lab";

    location / {
        try_files $uri $uri/ =404;
    }
}